name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    name:Test
    runs-on: ubuntu-latest

lint:
  name: Lint
  runs-on: ubuntu-latest
  steps:
    - name: checkout Repo
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15

- name: Use PostgreSQL
  uses: harmon758/postgresql-action@v1
  with:
    postgresql db: 'nc_news'
    postgresql user: 'test_user'
    postgresql password: 'test_password'

- name: Install dependencies
  run: npm ci

- name: Run tests
  run: PGDATABASE=nc_news PGUSER=test_user PGPASWORD=test_password npm t

deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

      - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL_ADDRESS }}

  




